[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DS3 Docs"
authors = [{name = "Pulsfort", email = "pulsfortjf@appstate.edu"}]
dynamic = ["version", "description"]
